SELECT P.PRODUCT_CODE, SUM(P.PRICE*O.SALES_AMOUNT) as SALES
FROM PRODUCT as P 
  INNER JOIN OFFLINE_SALE as O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SUM(P.PRICE*O.SALES_AMOUNT) DESC, PRODUCT_CODE