SELECT u.USER_ID, u.NICKNAME, b.TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
) b JOIN USED_GOODS_USER AS u ON b.WRITER_ID = u.USER_ID
WHERE b.TOTAL_SALES >= 700000
ORDER BY b.TOTAL_SALES