SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN (
SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
FROM FISH_INFO
GROUP BY FISH_TYPE
) AS M ON I.FISH_TYPE = M.FISH_TYPE AND M.MAX_LEN = I.LENGTH
JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY I.ID;
