SELECT SUM(gr.SCORE) as SCORE, em.EMP_NO, em.EMP_NAME, em.POSITION, em.EMAIL
FROM HR_EMPLOYEES as em
INNER JOIN HR_GRADE as gr on em.EMP_NO = gr.EMP_NO
GROUP BY gr.EMP_NO
ORDER BY SUM(gr.SCORE) DESC LIMIT 1